<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body class="bg-dark text-light">
<h2>Editar Cadastro</h2>

<?php
    // Abre o formulário usando o Phalcon
    foreach($cliente as $clienteItem) { 
    echo $this->tag->form(["cliente/atualizar/$clienteItem->id", "method" => "POST"]);
      ?>
      
      <div class="form-group">
        <label>Nome</label>
        <?php
            // Cria um campo de texto para o nome usando o Phalcon
            echo $this->tag->textField(
                [
                    "nome",
                    "class" => "form-control",
                    "value" => $clienteItem->nome,
                    "required" => true,
                ]
            );
        ?>
    </div>

    <div class="form-group">
        <label>E-mail</label>
        <?php
            // Cria um campo de texto para o e-mail usando o Phalcon
            echo $this->tag->textField(
                [
                    "email",
                    "class" => "form-control",
                    "value" => $clienteItem->email,
                    "required" => true,
                ]
            );
        ?>
    </div>

    <div class="form-group">
        <label>Data Nascimento</label>
        <?php
            // Cria um campo de texto para o e-mail usando o Phalcon
            
            echo $this->tag->textField(
                [
                    "data_nascimento",
                    "id" => "data_nascimento",
                    "class" => "form-control",
                    "value" => date('d/m/Y', strtotime($clienteItem->data_nascimento)),
                    "type" => "number",
                    "required" => true,
                ]
            );
        ?>
    </div>

    <!-- Seção do formulário para telefones -->
<div class="form-group" id="telefones-container">
    <label>Telefones</label>

    <?php foreach ($clienteItem->getTelefones() as $indice => $telefone) { ?>
        <div class="telefone-item">
            <?php
                echo $this->tag->textField(
                    [
                        "telefones[$indice][numero]",
                        "class" => "form-control mb-3",
                        "value" => $telefone->numero,
                        "type" => "number",
                        "required" => true,
                    ]
                );
            ?>
        </div>
    <?php } ?>
</div>


        

    <div class="form-group">
        <?php
            // Cria um botão de envio usando o Phalcon e adiciona a classe
            //primeiro parametro é controller e segundo / metodo
            echo $this->tag->submitButton(["Salvar", 'class' => 'btn btn-success m-2']);
            echo $this->tag->linkTo(["/", "Cancelar", 'class' => 'btn btn-danger m-2']);
        ?>
    </div>

<?php
    // Fecha o formulário
    echo $this->tag->endForm();
?>
<?php } ?>
</body>

<script src="https://unpkg.com/imask"></script>

<script>
    $(document).ready(function () {
        // Contador para gerar IDs únicos
        let contador = <?= count($clienteItem->getTelefones()) + 1 ?>; // Começa com um número maior que a quantidade de telefones existentes

        // Manipular ação de clique no botão "Adicionar Outro Telefone"
        $("#adicionar-telefone").click(function () {
            // Clonar o campo de telefone
            let novoCampo = $("#telefones-container").clone();

            // Atualizar IDs e nome do campo clonado
            novoCampo.find("input").attr("id", "numero_" + contador).attr("name", "numero[]");

            // Limpar o valor do campo clonado
            novoCampo.find("input").val('');

            // Incrementar o contador para futuros campos
            contador++;

            // Adicionar o novo campo ao contêiner
            $("#telefones-container").after(novoCampo);
        });
    });
</script>

<script>

    IMask(
        document.getElementById('data_nascimento'),
       {
        mask: '00/00/0000'
       }
    )

    function teste($mensagem){
        return alert($mensagem); 
    }

</script>

</html>